### ISSUE TITLE
First calibration - Retry does not re-position

### ISSUE THREAD

**Issue by deflektor** [FABtotum/FAB-UI#29]
Hi all!

If the First Calibration is executed - and you are asked if you want to go "previous" - "Calibrate" - "next". And you press Calibrate again, the system does not re-position the head, instead thinks the head did not move at all.

I think better would be a re-initialization. And the number of probes is increased. If you have to play the "Calibration" again, the number of probes increase further (had 14 probes per corner).

I did not found the place where I could replace the lines, so that the calibration is done after a reset again.

**Comment by christopherwit** [comment]
I did not try to replicate your issue. But I now if you alter line 57 of \fabui\application\modules\maintenance\views\bedcalibration\js.php to state num_probes =1; the number of probes on retest won't increase.

When I have the printer running I will try to reproduce your issue.

**Comment by deflektor** [comment]
Hi Christopher!

I think the initial value is 3 - so if you could comment the line or check if the value is less than 3, should solve the increase of probes per corner.

Do you also have an idea, how a re-calibrate could be forced to check where the head (X, Y) is positioned?

Thanks!

**Comment by christopherwit** [comment]
i totally forgot about reproducing your issue. Currently mu setup isn't stock since I try to fit a pi3.

It should be fairly easy for the fabteam to add some code to reposition X and Y which I agree would be better from a safety perspective during a recalibration.
Because steppers are powered down while adjusting the bed level screws it is fairly easy to move the head for whatever reason out of position between calibrations with all resulting affects.

At kriosmane; would it be possible to code a initialization for X and Y on a consecutive calibration?
